# Site wide configuration

title: Fashioncat
description: "The go-to source for internet fashion"
logo: # 120x120 px default image used for Twitter summary card
teaser: # 400x250 px default teaser image used in image archive grid
locale: en_US
url:

# Jekyll configuration

sass:
    sass_dir: _sass
    style: compressed
permalink: /:categories/:title/
markdown: kramdown
highlighter: pygments
gems:
  - jekyll-sitemap


# Site owner
owner:
  name: Katie Renarde
  email: katierenarde@gmail.com
  twitter:
  google:
    ad-client:
    ad-slot:
  bio: "A bored girl from a small town, Katie was in desperate need to do something- so she created this blog. Culled from various fashion forums and real life, Fashioncat is the go-to source for what's currently happening! When she's not lurking threads on 4chan, Katie is usually eating, working, or sleeping- the perfect life for a cat"
  avatar: bio-photo.jpg # 160x160 px image for author byline
disqus-shortname:


exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
